name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true

permissions:
  contents: write
  id-token: write 

jobs:

  release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:

      # see https://github.com/marketplace/actions/download-workflow-artifact
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_wheels.yml
          path: wheels

      - name: List and move wheels
        run: |
          mkdir dist
          find wheels -name "*.whl" -exec bash -c 'mv "$1" "dist/$(basename "$1" .whl)_$(basename $(dirname "$1")).whl"' _ {} \;
          rm -rf wheels
          ls dist

      # see https://github.com/marketplace/actions/create-release
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.whl"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.tag }}
